title: Hisam's JTD
description: Hisam's Just the Docs personal template
theme: just-the-docs

url: https://hisamafahri.github.io/template-jtd

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/hisamafahri/template-jtd
